---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8s-assignment-2.my.domain
  resources:
  - flighttickets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8s-assignment-2.my.domain
  resources:
  - flighttickets/finalizers
  verbs:
  - update
- apiGroups:
  - k8s-assignment-2.my.domain
  resources:
  - flighttickets/status
  verbs:
  - get
  - patch
  - update
